// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3H1EXm4qAQ5i2PtFC0xvreHeQs9hldg',
    appId: '1:1097353746059:web:4394114f2149717c50268e',
    messagingSenderId: '1097353746059',
    projectId: 'just-chat-app-6b126',
    authDomain: 'just-chat-app-6b126.firebaseapp.com',
    storageBucket: 'just-chat-app-6b126.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhvhQ7Rgt3g0PauNxCpqrvx_0Tit-INxk',
    appId: '1:1097353746059:android:414a01e09a5791f550268e',
    messagingSenderId: '1097353746059',
    projectId: 'just-chat-app-6b126',
    storageBucket: 'just-chat-app-6b126.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOPm8juDpYZR4AJ82Z1dhZO2CetcM0VBo',
    appId: '1:1097353746059:ios:9769fe20e892c42a50268e',
    messagingSenderId: '1097353746059',
    projectId: 'just-chat-app-6b126',
    storageBucket: 'just-chat-app-6b126.firebasestorage.app',
    iosBundleId: 'com.example.justChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOPm8juDpYZR4AJ82Z1dhZO2CetcM0VBo',
    appId: '1:1097353746059:ios:9769fe20e892c42a50268e',
    messagingSenderId: '1097353746059',
    projectId: 'just-chat-app-6b126',
    storageBucket: 'just-chat-app-6b126.firebasestorage.app',
    iosBundleId: 'com.example.justChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN3H1EXm4qAQ5i2PtFC0xvreHeQs9hldg',
    appId: '1:1097353746059:web:b873a4e3b48f3efe50268e',
    messagingSenderId: '1097353746059',
    projectId: 'just-chat-app-6b126',
    authDomain: 'just-chat-app-6b126.firebaseapp.com',
    storageBucket: 'just-chat-app-6b126.firebasestorage.app',
  );
}
